### ISSUE TITLE
Add DeleteFiles in the NPM package install

### ISSUE THREAD

**Issue by jimior2** [RickStrahl/DeleteFiles#2]
Hi, is possible to install this tool from npm package that we could install globally for use?
This tool help me lot to remove npm nested package when the file name lager than windows support.

**Comment by RickStrahl** [comment]
npm is intended to run node programs not exe's - so I'm not sure how to even create a package for NPM that works off an exe. Nor would this be cross platform and working on anything but Windows.

That's what Chocolatey or OneGet are for - you can use either to install DeleteFiles from a package manager.

**Comment by jimior2** [comment]
@RickStrahl  got it, Thanks,. this tool really helpful.
